Update statistic_functions.py
joosthoeks/jhTAlib pull request #18
Opened 2021-07-22 12:50 UTC by nailcankara

2021-07-28 18:02 UTC, joosthoeks commented
I don't understand why you want to change this. Please explain.

2026-07-08 21:13 UTC, febuz commented on jhtalib/statistic_functions/statistic_functions.py
> +            y_list = list(df[price][start:end].values)
Alleen relevant voor pandas, dit is niet onderdeel van het pure python pakket
Only relevant for pandas, this is not part of the pure python package

2026-07-08 21:14 UTC, febuz requested changes
Drop this PR or argument against 'only relevant pandas' argument

2026-07-08 21:50 UTC, febuz commented on jhtalib/statistic_functions/statistic_functions.py
> +            y_list = list(df[price][start:end].values)
Omdat jhta.REGRESSION puur positioneel indexeert, en een pandas Series-slice dat niet doet. Dit is de kern van REGRESSION in dezelfde file:
pythonfor i in range(len(x_list)):
    x = x_list[i]
    y = y_list[i]   # <- positionele index, begint bij 0
Als df een DataFrame is, geeft df[price][start:end] een Series terug die zijn oorspronkelijke index-labels behoudt (start t/m end-1). En scalar []-access op een Series met integer-index is label-based, niet positioneel. Dus zodra start ≥ 1 bestaat label 0 niet meer:
python>>> s = pd.Series([10., 11., 12., 13., 14.])
>>> w = s[2:5]          # window vanaf de 2e LSMA-iteratie
>>> list(w.index)
[2, 3, 4]
>>> w[0]
KeyError: 0
Het venijnige is dat de eerste window (start=0) toevallig wél werkt omdat labels en posities daar samenvallen — de bug verschijnt pas vanaf iteratie twee. Met .values strip je de index (numpy array), en list(...) maakt er een kale positionele container van, precies wat REGRESSION verwacht. Bijkomend: REGRESSION wrapt y_list ook nog in jhta.SUM({'y_list': y_list}, ...), en de hele library is geschreven in die dict-of-lists/while-loop-stijl, dus een Series doorgeven is daar overal vragen om problemen.
Twee kanttekeningen bij de fix zelf. Ten eerste had list(df[price][start:end]) zónder .values hetzelfde bereikt (itereren over een Series levert gewoon de values op) — en dat zou bovendien backwards compatible zijn met jhTAlib's oorspronkelijke dict-of-lists input, waar .values juist een AttributeError geeft op een gewone list-slice. Deze patch pint de functie dus impliciet vast op pandas-input. Ten tweede geeft list(arr.values) je np.float64-objecten in plaats van native Python floats; voor de rekenkunde maakt dat niets uit, maar .tolist() was de nettere variant geweest (en .to_numpy() de modernere API dan .values).

2026-07-08 21:50 UTC, febuz commented on jhtalib/statistic_functions/statistic_functions.py
> +            y_list = list(df[price][start:end].values)
https://claude.ai/share/0d507751-e3e9-4e5e-9d18-75bb0ee03636

2026-07-08 21:51 UTC, febuz commented on jhtalib/statistic_functions/statistic_functions.py
> +            y_list = list(df[price][start:end].values)
@nailcankara correct?

2026-07-11 05:55 UTC, merged